---
- name: Download JDK
  package:
    name: java
    state: present

- name: Check Java version
  command: java -version
  register: java_version

- name: Print Java version
  debug:
    msg: "{{ java_version }}"

- name: Fetch JAVA_HOME environment variable
  command: echo $JAVA_HOME
  register: java_home

- debug:
    var: java_home