---
- name: Download JDK
  package:
    name: java
    state: present

- name: Check Java version
  shell: java -version
  register: java_version

- name: Print Java version
  debug:
    msg: "{{ java_version }}"

- name: Set JAVA HOME environment variable
  shell: echo JAVA_HOME is $JAVA_HOME
  environment:
    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
  register: shellout

- debug:
    var: shellout